org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
fabric_loom_version=1.17.21
fabric_loader_version=0.19.5
fabric_api_version=0.158.0+26.2

mod_id=mine_chatcorrect
mod_name=Mine-ChatCorrect
mod_license=MIT
mod_version=0.1.3
mod_group_id=com.kaiki.minechatcorrect
mod_authors=Kaiki
mod_description=Client-side chat spell checking for Minecraft Fabric.
